import Head from "next/head";
import { SignIn, useUser } from "@clerk/nextjs";

import { RouterOutputs, api } from "~/utils/api";


const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  console.warn('user', user);

  return <div className="flex gap-3 w-full">
    <img src={user.imageUrl} alt="Profile image" className="h-14 w-14 rounded-full" />

    <input placeholder="Type some emojis!" className="grow bg-transparent outline-none" />
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return <div key={post.id} className="border-b border-slate-400 p-8">{post.content}</div>
}


export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();
  console.warn('data', data);

  if (!data || isLoading) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-x border-slate-200 md:max-w-2xl">

          <div className="flex justify-center border-b border-slate-400 p-4">
            {user?.isSignedIn ? (
              <CreatePostWizard />
            ) : <SignIn />}


          </div>

          <div className="flex flex-col">
            {data.map((fullPost) => <PostView {...fullPost} key={fullPost.post.id} />)}
          </div>
        </div>
      </main>
    </>
  );
}
